#!/bin/bash

# MySQL Permissions Setup for Great Leap App
# Run this ONCE on the production server to enable tenant database creation

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Great Leap App - MySQL Permissions Setup                   ║"
echo "║     This script grants permissions to create tenant databases  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Server details
SERVER_IP="168.144.67.229"
DB_USER="greatleap_user"
DB_PASSWORD="GreatLeap@2026"

echo "Server: $SERVER_IP"
echo "Database User: $DB_USER"
echo ""

# Step 1: Connect to server
echo "Step 1: Connecting to server..."
echo "Command: ssh ubuntu@$SERVER_IP"
echo ""

# Step 2: Run MySQL command
echo "Step 2: Once connected, run this command:"
echo ""
echo "mysql -u root -p << EOF"
echo "-- Grant permissions to create tenant databases"
echo "GRANT ALL PRIVILEGES ON \`tenant_%\`.* TO '$DB_USER'@'localhost';"
echo "-- Flush privileges to apply changes"
echo "FLUSH PRIVILEGES;"
echo "-- Verify the grant was successful"
echo "SHOW GRANTS FOR '$DB_USER'@'localhost';"
echo "EOF"
echo ""

echo "Step 3: Expected output should show:"
echo "GRANT ALL PRIVILEGES ON \`tenant_%\`.* TO 'greatleap_user'@'localhost'"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ HOW TO RUN THIS                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Option A: Copy-Paste (Recommended)"
echo "─────────────────────────────────────"
echo "1. Open your terminal/SSH client"
echo "2. Run: ssh ubuntu@$SERVER_IP"
echo "3. When prompted for password, enter your SSH key or password"
echo "4. Once connected, paste this entire block:"
echo ""
echo "mysql -u root -p << EOF"
echo "GRANT ALL PRIVILEGES ON \`tenant_%\`.* TO '$DB_USER'@'localhost';"
echo "FLUSH PRIVILEGES;"
echo "SHOW GRANTS FOR '$DB_USER'@'localhost';"
echo "EOF"
echo ""
echo "5. When prompted for MySQL password, enter: (ask admin)"
echo "6. You should see output showing the grant was applied"
echo ""
echo ""

echo "Option B: Using This Script (Advanced)"
echo "──────────────────────────────────────"
echo "1. Save this file as setup-mysql-permissions.sh"
echo "2. Make it executable: chmod +x setup-mysql-permissions.sh"
echo "3. Run via SSH: ssh ubuntu@$SERVER_IP 'bash -s' < setup-mysql-permissions.sh"
echo ""
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║ WHAT HAPPENS AFTER                                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "After the grant is successful:"
echo ""
echo "1. Tenant databases can now be created automatically"
echo "2. When you create a new tenant via API:"
echo "   - Database: tenant_<uuid> is created"
echo "   - Migrations run automatically"
echo "   - Admin user is created in tenant DB"
echo ""
echo "3. Test by creating a tenant:"
echo "   curl -X POST http://168.144.67.229/api/tenants \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Authorization: Bearer <token>' \\"
echo "     -d '{\"company_name\": \"Test\", \"admin_name\": \"Admin\", \"admin_email\": \"admin@test.com\", \"admin_password\": \"Password123\", \"plan\": \"free\"}'"
echo ""
echo "4. Verify database created:"
echo "   mysql -u greatleap_user -p -h 127.0.0.1 -e 'SHOW DATABASES LIKE \"tenant_%\";'"
echo ""
